package telas;

import javax.swing.JOptionPane;
import classes.Proprietario;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author theo
 */
public class CadastroProprietário extends javax.swing.JFrame {
    static String nomeProp;

    /**
     * Creates new form CadastroProprietário
     */
    public CadastroProprietário() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeProp = new javax.swing.JLabel();
        txtNomeProp = new javax.swing.JTextField();
        lblCPFPRop = new javax.swing.JLabel();
        txtCpfProp = new javax.swing.JTextField();
        lblDataNasProp = new javax.swing.JLabel();
        txtDataNasProp = new javax.swing.JTextField();
        lblRendaProp = new javax.swing.JLabel();
        txtRendaProp = new javax.swing.JTextField();
        btnCadastrarProp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Proprietário");

        lblNomeProp.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblNomeProp.setText("Nome do Proprietário");

        lblCPFPRop.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCPFPRop.setText("CPF");

        lblDataNasProp.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblDataNasProp.setText("Data de nascimento");

        lblRendaProp.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblRendaProp.setText("Renda Mensal");

        btnCadastrarProp.setText("CADASTRAR");
        btnCadastrarProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPropActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNomeProp)
                            .addComponent(txtNomeProp)
                            .addComponent(lblCPFPRop)
                            .addComponent(txtCpfProp)
                            .addComponent(lblDataNasProp)
                            .addComponent(txtDataNasProp)
                            .addComponent(lblRendaProp)
                            .addComponent(txtRendaProp, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(btnCadastrarProp)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeProp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeProp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCPFPRop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCpfProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDataNasProp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataNasProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRendaProp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRendaProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrarProp)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPropActionPerformed
        if(txtCpfProp.getText().equals("")|| txtDataNasProp.getText().equals("")|| txtNomeProp.getText().equals("")|| txtRendaProp.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Preencha todos os campos!","mensagem", JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Proprietário cadastrado com sucesso!");
            
            String nome = txtNomeProp.getText();
            CadastroProprietário.nomeProp = nome;
            Long cpf = Long.parseLong(txtCpfProp.getText());
            String datanas = txtDataNasProp.getText();
            Double renda = Double.parseDouble(txtRendaProp.getText());
            
            Proprietario proprietario = new Proprietario(nome,cpf,datanas,renda);
       
            this.dispose();
        }
    }//GEN-LAST:event_btnCadastrarPropActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProprietário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProprietário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProprietário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProprietário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProprietário().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarProp;
    private javax.swing.JLabel lblCPFPRop;
    private javax.swing.JLabel lblDataNasProp;
    private javax.swing.JLabel lblNomeProp;
    private javax.swing.JLabel lblRendaProp;
    private javax.swing.JTextField txtCpfProp;
    private javax.swing.JTextField txtDataNasProp;
    private javax.swing.JTextField txtNomeProp;
    private javax.swing.JTextField txtRendaProp;
    // End of variables declaration//GEN-END:variables
}
