/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JOptionPane;
import classes.Pasto;
import classes.Fazenda;
import java.util.ArrayList;
import telas.Principal;

/**
 *
 * @author theo
 */
public class CadastroPastos extends javax.swing.JFrame {
   
    
    /**
     * Creates new form CadastroPastos
     */
    public CadastroPastos() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomePasto = new javax.swing.JLabel();
        txtNOmePAsto = new javax.swing.JTextField();
        lblCapimPasto = new javax.swing.JLabel();
        txtCapimPasto = new javax.swing.JTextField();
        lblCapMaxPasto = new javax.swing.JLabel();
        txtCapPasto = new javax.swing.JTextField();
        lblCercaPasto = new javax.swing.JLabel();
        jradioSimcercaPasto = new javax.swing.JRadioButton();
        jradioNaoCercaPasto = new javax.swing.JRadioButton();
        btnCadastrarPasto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNomePasto.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblNomePasto.setText("Nome do pasto");

        lblCapimPasto.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCapimPasto.setText("Tipo do capim");

        txtCapimPasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapimPastoActionPerformed(evt);
            }
        });

        lblCapMaxPasto.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCapMaxPasto.setText("Capacidade máxima");

        lblCercaPasto.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCercaPasto.setText("Cerca está boa?");

        jradioSimcercaPasto.setText("Sim");
        jradioSimcercaPasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradioSimcercaPastoActionPerformed(evt);
            }
        });

        jradioNaoCercaPasto.setText("Não");
        jradioNaoCercaPasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradioNaoCercaPastoActionPerformed(evt);
            }
        });

        btnCadastrarPasto.setText("CADASTRAR");
        btnCadastrarPasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPastoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblNomePasto)
                                .addComponent(txtNOmePAsto)
                                .addComponent(lblCapimPasto)
                                .addComponent(txtCapimPasto, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                .addComponent(lblCapMaxPasto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCapPasto)
                                .addComponent(lblCercaPasto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jradioSimcercaPasto)
                                .addGap(18, 18, 18)
                                .addComponent(jradioNaoCercaPasto))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnCadastrarPasto)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomePasto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNOmePAsto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCapimPasto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCapimPasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCapMaxPasto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCapPasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCercaPasto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jradioSimcercaPasto)
                    .addComponent(jradioNaoCercaPasto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrarPasto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCapimPastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapimPastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapimPastoActionPerformed

    private void jradioNaoCercaPastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradioNaoCercaPastoActionPerformed
        if(jradioSimcercaPasto.isEnabled()){
            jradioSimcercaPasto.setEnabled(false);
        }else{
            jradioSimcercaPasto.setEnabled(true);
        }
    }//GEN-LAST:event_jradioNaoCercaPastoActionPerformed

    private void btnCadastrarPastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPastoActionPerformed
        if(txtCapPasto.getText().equals("")|| txtCapimPasto.getText().equals("")|| txtNOmePAsto.getText().equals("")||(!jradioNaoCercaPasto.isSelected() && !jradioSimcercaPasto.isSelected())){
            JOptionPane.showMessageDialog(null,"Preencha todos os campos!","mensagem", JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Pasto cadastrado com sucesso!");
            
            boolean cercaboa = true;
            String nome = txtNOmePAsto.getText();
            String capim = txtCapimPasto.getText();
            int cap = Integer.parseInt(txtCapPasto.getText());
            if(jradioNaoCercaPasto.isSelected()){
                cercaboa = false;
            }
            
            Pasto pasto = new Pasto(nome,capim,cap,cercaboa);
            
            Principal.listaPastos.add(pasto);
            
            this.dispose();
        }
    }//GEN-LAST:event_btnCadastrarPastoActionPerformed

    private void jradioSimcercaPastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradioSimcercaPastoActionPerformed
        if(jradioNaoCercaPasto.isEnabled()){
            jradioNaoCercaPasto.setEnabled(false);
        }else{
            jradioNaoCercaPasto.setEnabled(true);
        }
        
    }//GEN-LAST:event_jradioSimcercaPastoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPastos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarPasto;
    private javax.swing.JRadioButton jradioNaoCercaPasto;
    private javax.swing.JRadioButton jradioSimcercaPasto;
    private javax.swing.JLabel lblCapMaxPasto;
    private javax.swing.JLabel lblCapimPasto;
    private javax.swing.JLabel lblCercaPasto;
    private javax.swing.JLabel lblNomePasto;
    private javax.swing.JTextField txtCapPasto;
    private javax.swing.JTextField txtCapimPasto;
    private javax.swing.JTextField txtNOmePAsto;
    // End of variables declaration//GEN-END:variables
}
