package telas;

import classes.Funcionario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import telas.CadastroFazenda;
import telas.Principal;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author theo
 */
public class CadastroFuncionário extends javax.swing.JFrame {
    
        

    //static ArrayList<Funcionario> listafuncionarios;
   
    
    /**
     * Creates new form CadastroProprietário
     */
    public CadastroFuncionário() {
        initComponents();
        
        
        //listafuncionarios = new ArrayList();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeFunc = new javax.swing.JLabel();
        txtNomeFunc = new javax.swing.JTextField();
        lblCPFFunc = new javax.swing.JLabel();
        txtCpfFunc = new javax.swing.JTextField();
        lblDataNasFunc = new javax.swing.JLabel();
        txtDataNasFunc = new javax.swing.JTextField();
        lblSalarioFunc = new javax.swing.JLabel();
        txtSalarioFunc = new javax.swing.JTextField();
        btnCadastrarFunc = new javax.swing.JButton();
        lblFuncaoFunc = new javax.swing.JLabel();
        txtFuncFunc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNomeFunc.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblNomeFunc.setText("Nome do funcionário");

        lblCPFFunc.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCPFFunc.setText("CPF");

        lblDataNasFunc.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblDataNasFunc.setText("Data de nascimento");

        lblSalarioFunc.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblSalarioFunc.setText("Salário");

        btnCadastrarFunc.setText("CADASTRAR");
        btnCadastrarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFuncActionPerformed(evt);
            }
        });

        lblFuncaoFunc.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblFuncaoFunc.setText("Função");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNomeFunc)
                            .addComponent(txtNomeFunc)
                            .addComponent(lblCPFFunc)
                            .addComponent(txtCpfFunc)
                            .addComponent(lblDataNasFunc)
                            .addComponent(txtDataNasFunc)
                            .addComponent(lblSalarioFunc)
                            .addComponent(txtSalarioFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(lblFuncaoFunc)
                            .addComponent(txtFuncFunc)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(btnCadastrarFunc)))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCPFFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCpfFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDataNasFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataNasFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSalarioFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSalarioFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFuncaoFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFuncFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnCadastrarFunc)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFuncActionPerformed
        if(txtCpfFunc.getText().equals("")|| txtDataNasFunc.getText().equals("")|| txtNomeFunc.getText().equals("")|| txtSalarioFunc.getText().equals("") || txtCpfFunc.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Preencha todos os campos!","mensagem", JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Funcionário cadastrado com sucesso!");
            
            String nome = txtNomeFunc.getText();
            Long cpf = Long.parseLong(txtCpfFunc.getText());
            String datanas = txtDataNasFunc.getText();
            String funçao = txtFuncFunc.getText();
            Double salario = Double.parseDouble(txtSalarioFunc.getText());
            
            Funcionario funcionario = new Funcionario(nome,cpf,datanas, funçao, salario);
            
            
            
            Principal.listafuncionarios.add(funcionario);
           
            this.dispose();
        }
        
    }//GEN-LAST:event_btnCadastrarFuncActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFuncionário().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarFunc;
    private javax.swing.JLabel lblCPFFunc;
    private javax.swing.JLabel lblDataNasFunc;
    private javax.swing.JLabel lblFuncaoFunc;
    private javax.swing.JLabel lblNomeFunc;
    private javax.swing.JLabel lblSalarioFunc;
    private javax.swing.JTextField txtCpfFunc;
    private javax.swing.JTextField txtDataNasFunc;
    private javax.swing.JTextField txtFuncFunc;
    private javax.swing.JTextField txtNomeFunc;
    private javax.swing.JTextField txtSalarioFunc;
    // End of variables declaration//GEN-END:variables
}
