/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import telas.CadastroProprietário;
import telas.Principal;

/**
 *
 * @author theo
 */
public class CaracterisiticasFaz extends javax.swing.JFrame {

    /**
     * Creates new form CaracterisiticasFaz
     */
    public CaracterisiticasFaz() {
        initComponents();
        this.txtRecebeNomeProp.setText(CadastroProprietário.nomeProp);
        this.txtRecebeTotalFunc.setText(String.valueOf(Principal.listafuncionarios.size()));
        this.txtRecebeTotalanimais.setText(String.valueOf(Principal.listaAnimais.size()));
        this.txtRecebetotalpastos.setText(String.valueOf(Principal.listaPastos.size()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfomsgCaracFaz = new javax.swing.JLabel();
        lblNomeProp = new javax.swing.JLabel();
        txtRecebeNomeProp = new javax.swing.JTextField();
        txtRecebeTotalFunc = new javax.swing.JTextField();
        lblTotalFunc = new javax.swing.JLabel();
        lbltotalpsstos = new javax.swing.JLabel();
        txtRecebetotalpastos = new javax.swing.JTextField();
        lblTotalGado = new javax.swing.JLabel();
        txtRecebeTotalanimais = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblInfomsgCaracFaz.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblInfomsgCaracFaz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconDadosDados.png"))); // NOI18N
        lblInfomsgCaracFaz.setText("Características da fazenda");

        lblNomeProp.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblNomeProp.setText("Nome do proprietário:");

        txtRecebeNomeProp.setEditable(false);

        txtRecebeTotalFunc.setEditable(false);

        lblTotalFunc.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblTotalFunc.setText("Total de funcionários:");

        lbltotalpsstos.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lbltotalpsstos.setText("Total de pastos:");

        lblTotalGado.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblTotalGado.setText("Total de animais:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(lblInfomsgCaracFaz, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeProp)
                            .addComponent(lblTotalFunc)
                            .addComponent(lbltotalpsstos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalGado))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRecebeNomeProp, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtRecebeTotalanimais, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                .addComponent(txtRecebetotalpastos, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtRecebeTotalFunc, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfomsgCaracFaz)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblNomeProp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(txtRecebeNomeProp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRecebeTotalFunc)
                    .addComponent(lblTotalFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRecebetotalpastos)
                    .addComponent(lbltotalpsstos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalGado)
                    .addComponent(txtRecebeTotalanimais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaracterisiticasFaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaracterisiticasFaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaracterisiticasFaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaracterisiticasFaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaracterisiticasFaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblInfomsgCaracFaz;
    private javax.swing.JLabel lblNomeProp;
    private javax.swing.JLabel lblTotalFunc;
    private javax.swing.JLabel lblTotalGado;
    private javax.swing.JLabel lbltotalpsstos;
    private javax.swing.JTextField txtRecebeNomeProp;
    private javax.swing.JTextField txtRecebeTotalFunc;
    private javax.swing.JTextField txtRecebeTotalanimais;
    private javax.swing.JTextField txtRecebetotalpastos;
    // End of variables declaration//GEN-END:variables
}
