/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JOptionPane;
import classes.Gado;
import java.util.ArrayList;
import telas.Principal;
import telas.TabelaGado;

/**
 *
 * @author theo
 */
public class EdiçaoGado extends javax.swing.JFrame {
    static String raca;
    static String sexo;
    static String pasto;
    static int id;
    static int idade;
    static boolean vacinado;
     
    
    /**
     * Creates new form CadastroGado
     */
    public EdiçaoGado() {
        initComponents();
        this.txtIDGado.setText(String.valueOf(id));
        this.txtRacaGado.setText(raca);
        this.txtSexoGado.setText(sexo);
        this.txtIdadeGado.setText(String.valueOf(idade));
        this.txtPastoGado.setText(pasto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRacaGado = new javax.swing.JLabel();
        txtRacaGado = new javax.swing.JTextField();
        lblSexoGado = new javax.swing.JLabel();
        txtSexoGado = new javax.swing.JTextField();
        lblIDadeGado = new javax.swing.JLabel();
        txtIdadeGado = new javax.swing.JTextField();
        lblIDGado = new javax.swing.JLabel();
        txtIDGado = new javax.swing.JTextField();
        lblVacinaçãoGado = new javax.swing.JLabel();
        jradioSimVAcinaGAdo = new javax.swing.JRadioButton();
        jradioNaoVacinaGado = new javax.swing.JRadioButton();
        btnCadastrarGado = new javax.swing.JButton();
        lblPastoGado = new javax.swing.JLabel();
        txtPastoGado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblRacaGado.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblRacaGado.setText("Raça");

        txtRacaGado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRacaGadoActionPerformed(evt);
            }
        });

        lblSexoGado.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblSexoGado.setText("Sexo(M ou F)");

        txtSexoGado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexoGadoActionPerformed(evt);
            }
        });

        lblIDadeGado.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblIDadeGado.setText("Idade(meses)");

        lblIDGado.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblIDGado.setText("Número do brinco de identificação");

        txtIDGado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDGadoActionPerformed(evt);
            }
        });

        lblVacinaçãoGado.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblVacinaçãoGado.setText("Vacinação em dia");

        jradioSimVAcinaGAdo.setText("Sim");
        jradioSimVAcinaGAdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradioSimVAcinaGAdoActionPerformed(evt);
            }
        });

        jradioNaoVacinaGado.setText("Não");
        jradioNaoVacinaGado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradioNaoVacinaGadoActionPerformed(evt);
            }
        });

        btnCadastrarGado.setText("Salvar mudanças");
        btnCadastrarGado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarGadoActionPerformed(evt);
            }
        });

        lblPastoGado.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblPastoGado.setText("Pasto");

        txtPastoGado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPastoGadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIDGado)
                    .addComponent(txtIDGado, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblRacaGado)
                        .addComponent(txtRacaGado)
                        .addComponent(lblSexoGado)
                        .addComponent(txtSexoGado)
                        .addComponent(lblIDadeGado)
                        .addComponent(txtIdadeGado, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                    .addComponent(lblVacinaçãoGado)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jradioSimVAcinaGAdo)
                        .addGap(18, 18, 18)
                        .addComponent(jradioNaoVacinaGado))
                    .addComponent(lblPastoGado)
                    .addComponent(txtPastoGado, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(190, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrarGado, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRacaGado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRacaGado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSexoGado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSexoGado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIDadeGado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdadeGado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIDGado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIDGado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVacinaçãoGado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jradioSimVAcinaGAdo)
                    .addComponent(jradioNaoVacinaGado))
                .addGap(12, 12, 12)
                .addComponent(lblPastoGado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPastoGado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnCadastrarGado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtRacaGadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRacaGadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRacaGadoActionPerformed

    private void txtSexoGadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexoGadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexoGadoActionPerformed

    private void txtIDGadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDGadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDGadoActionPerformed

    private void jradioSimVAcinaGAdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradioSimVAcinaGAdoActionPerformed
        if(jradioNaoVacinaGado.isEnabled()){
            jradioNaoVacinaGado.setEnabled(false);
        }else{
            jradioNaoVacinaGado.setEnabled(true);
        }
    }//GEN-LAST:event_jradioSimVAcinaGAdoActionPerformed

    private void jradioNaoVacinaGadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradioNaoVacinaGadoActionPerformed
        if (jradioSimVAcinaGAdo.isEnabled()){
            jradioSimVAcinaGAdo.setEnabled(false);
        }else{
            jradioSimVAcinaGAdo.setEnabled(true);
        }
    }//GEN-LAST:event_jradioNaoVacinaGadoActionPerformed

    private void btnCadastrarGadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarGadoActionPerformed
       if(txtIDGado.getText().equals("")||txtPastoGado.getText().equals("")|| txtIdadeGado.getText().equals("")|| txtRacaGado.getText().equals("")|| txtSexoGado.getText().equals("") ||(!jradioNaoVacinaGado.isSelected() && !jradioSimVAcinaGAdo.isSelected())){
            JOptionPane.showMessageDialog(null,"Preencha todos os campos!","mensagem", JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Gado cadastrado com sucesso!");
            Principal.listaAnimais.get(TabelaGado.index).setRaca(this.txtRacaGado.getText());
            Principal.listaAnimais.get(TabelaGado.index).setBrinco(Integer.parseInt(this.txtIDGado.getText()));
            Principal.listaAnimais.get(TabelaGado.index).setIdade_em_meses(Integer.parseInt(this.txtIdadeGado.getText()));
            Principal.listaAnimais.get(TabelaGado.index).setPasto(this.txtPastoGado.getText());
            Principal.listaAnimais.get(TabelaGado.index).setSexo(this.txtSexoGado.getText());
            if(jradioSimVAcinaGAdo.isSelected()){
                Principal.listaAnimais.get(TabelaGado.index).setVacinado(true);
            }else{
                Principal.listaAnimais.get(TabelaGado.index).setVacinado(false);
            }
            
            JOptionPane.showMessageDialog(null, "Gado alterado com sucesso\nRecarregue a tabela para vizualizar as alterações...");
            
            this.dispose();
        }
    }//GEN-LAST:event_btnCadastrarGadoActionPerformed

    private void txtPastoGadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPastoGadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPastoGadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EdiçaoGado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EdiçaoGado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EdiçaoGado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EdiçaoGado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EdiçaoGado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarGado;
    private javax.swing.JRadioButton jradioNaoVacinaGado;
    private javax.swing.JRadioButton jradioSimVAcinaGAdo;
    private javax.swing.JLabel lblIDGado;
    private javax.swing.JLabel lblIDadeGado;
    private javax.swing.JLabel lblPastoGado;
    private javax.swing.JLabel lblRacaGado;
    private javax.swing.JLabel lblSexoGado;
    private javax.swing.JLabel lblVacinaçãoGado;
    private javax.swing.JTextField txtIDGado;
    private javax.swing.JTextField txtIdadeGado;
    private javax.swing.JTextField txtPastoGado;
    private javax.swing.JTextField txtRacaGado;
    private javax.swing.JTextField txtSexoGado;
    // End of variables declaration//GEN-END:variables
}
