/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import static java.lang.String.valueOf;
import telas.CadastroFazenda;
import telas.Principal;

/**
 *
 * @author theo
 */
public class EscrituraFaz extends javax.swing.JFrame {

    /**
     * Creates new form EscrituraFaz
     */
    public EscrituraFaz() {
        initComponents();
        this.txtRecebenomefaz.setText(CadastroFazenda.nome);
        this.txtRecebeAreaFaz.setText(String.valueOf(CadastroFazenda.area));
        this.txtRecebeInsFaz.setText(CadastroFazenda.escritura);
        this.txtRecebeLocFaz.setText(CadastroFazenda.loc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfomsgDocFAz = new javax.swing.JLabel();
        lblNomeFaz = new javax.swing.JLabel();
        txtRecebenomefaz = new javax.swing.JTextField();
        lblAreaFaz = new javax.swing.JLabel();
        txtRecebeAreaFaz = new javax.swing.JTextField();
        lblLocFaz = new javax.swing.JLabel();
        lblInsFaz = new javax.swing.JLabel();
        txtRecebeLocFaz = new javax.swing.JTextField();
        txtRecebeInsFaz = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblInfomsgDocFAz.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        lblInfomsgDocFAz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconEscritura.png"))); // NOI18N
        lblInfomsgDocFAz.setText("Documentação da fazenda:");

        lblNomeFaz.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblNomeFaz.setText("Nome da fazenda:");

        txtRecebenomefaz.setEditable(false);
        txtRecebenomefaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecebenomefazActionPerformed(evt);
            }
        });

        lblAreaFaz.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblAreaFaz.setText("Área da fazenda:");

        txtRecebeAreaFaz.setEditable(false);

        lblLocFaz.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblLocFaz.setText("Localização:");

        lblInsFaz.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblInsFaz.setText("Inscrição:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblInfomsgDocFAz)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNomeFaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAreaFaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInsFaz, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLocFaz, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRecebenomefaz)
                    .addComponent(txtRecebeAreaFaz)
                    .addComponent(txtRecebeLocFaz)
                    .addComponent(txtRecebeInsFaz, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfomsgDocFAz)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeFaz)
                    .addComponent(txtRecebenomefaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAreaFaz)
                    .addComponent(txtRecebeAreaFaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRecebeLocFaz)
                    .addComponent(lblLocFaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtRecebeInsFaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblInsFaz, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        lblLocFaz.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtRecebenomefazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecebenomefazActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecebenomefazActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscrituraFaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscrituraFaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscrituraFaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscrituraFaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscrituraFaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAreaFaz;
    private javax.swing.JLabel lblInfomsgDocFAz;
    private javax.swing.JLabel lblInsFaz;
    private javax.swing.JLabel lblLocFaz;
    private javax.swing.JLabel lblNomeFaz;
    private javax.swing.JTextField txtRecebeAreaFaz;
    private javax.swing.JTextField txtRecebeInsFaz;
    private javax.swing.JTextField txtRecebeLocFaz;
    private javax.swing.JTextField txtRecebenomefaz;
    // End of variables declaration//GEN-END:variables
}
