
        
        /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import telas.CadastroFuncionário;
import telas.Principal;
import telas.Ediçãofuncionário;
import classes.Funcionario;

/**
 *
 * @author theo
 */
public class ListaFuncionários extends javax.swing.JFrame {
    static int index;

    /**
     * Creates new form ListaFuncionários
     */
    public ListaFuncionários() {
        initComponents();
        
        DefaultTableModel tabela = new DefaultTableModel(new Object[]{"Nome","CPF","Nascimento","Função","Salário"}, 0);
        for(int i = 0; i < Principal.listafuncionarios.size(); i ++){
            Object linha = new Object[]{Principal.listafuncionarios.get(i).getNome(),
                                        Principal.listafuncionarios.get(i).getCpf(),
                                        Principal.listafuncionarios.get(i).getDataNasc(),
                                        Principal.listafuncionarios.get(i).getFuncao(),
                                        Principal.listafuncionarios.get(i).getSalario()};
                                           
            
            tabela.addRow((Object[]) linha);
            
            
       }
        
        tblFuncionarios.setModel(tabela);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RolagemFuncionarios = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        RolagemFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RolagemFuncionariosMouseClicked(evt);
            }
        });

        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Nascimento", "Função", "Salário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFuncionariosMouseClicked(evt);
            }
        });
        RolagemFuncionarios.setViewportView(tblFuncionarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RolagemFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RolagemFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RolagemFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RolagemFuncionariosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RolagemFuncionariosMouseClicked

    private void tblFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFuncionariosMouseClicked
        JOptionPane.showMessageDialog(null, "Você agora irá editar os dados do funcionário selecionado...");
        
        index = tblFuncionarios.getSelectedRow();
        Funcionario f1 = Principal.listafuncionarios.get(index);
        
        Ediçãofuncionário.nome2 = f1.getNome();
        Ediçãofuncionário.cpf2 = f1.getCpf();
        Ediçãofuncionário.datanas2 = f1.getDataNasc();
        Ediçãofuncionário.salario2 = f1.getSalario();
        Ediçãofuncionário.funçao2 = f1.getFuncao();
        new Ediçãofuncionário().setVisible(true);
    }//GEN-LAST:event_tblFuncionariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaFuncionários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaFuncionários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaFuncionários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaFuncionários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaFuncionários().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane RolagemFuncionarios;
    private javax.swing.JTable tblFuncionarios;
    // End of variables declaration//GEN-END:variables
}
